### PR TITLE
pytest

### PR DESCRIPTION
**Pull request by NoAmateur**
lhb

## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR

### CODE REVIEW

**Comment by NoAmateur** [comment]
pytest修改

**Comment by gyzhou2000** [comment]
utils：device, shortest_path, to_dense_adj
datasets: blogcatalog, dblp, ml, shapenet, webkb, wikipedia_network

**Comment by gyzhou2000** [comment]
datasets: zinc

**Comment by gyzhou2000** [comment]
transforms: vgae_pre

**Comment by gyzhou2000** [comment]
layers/attention: centrality_encoder, edge_encoder(tensorflow), spatial_encoder

**Comment by gyzhou2000** [comment]
layers/conv: compgcn_conv, fusedgat_conv(need dgNN package), iehgcn_conv, mgnni_m_iter

**Comment by gyzhou2000** [comment]
> layers/conv: compgcn_conv, fusedgat_conv(need dgNN package), iehgcn_conv, mgnni_m_iter

除了fusedgat_conv

**Comment by gyzhou2000** [comment]
> layers/attention: centrality_encoder, edge_encoder(tensorflow), spatial_encoder
doen

**Comment by gyzhou2000** [comment]
> transforms: vgae_pre

doen

**Pull request merged**
